spring:
  application:
    name: parking-reservation

  datasource:
    url: jdbc:postgresql://localhost:5432/parking
    username: parking
    password: parking

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

server:
  port: 8080